// Kinezi-AI Exercise Definitions
// Core exercise library with metadata, rules, and descriptions

export type ExerciseCategory = 'lower_body' | 'upper_body' | 'core' | 'full_body' | 'pilates';
export type Difficulty = 'beginner' | 'intermediate' | 'advanced';
export type MuscleGroup = 'quads' | 'hamstrings' | 'glutes' | 'chest' | 'back' | 'shoulders' | 'core' | 'arms' | 'calves';

export interface Exercise {
  id: string;
  name: string;
  nameTr: string;
  description: string;
  descriptionTr: string;
  category: ExerciseCategory;
  difficulty: Difficulty;
  muscleGroups: MuscleGroup[];
  icon: string;
  defaultSets: number;
  defaultReps: number;
  restSeconds: number;
  cameraPosition: 'side' | 'front';
  tips: string[];
  tipsTr: string[];
  demoUrl?: string;
}

export const EXERCISES: Exercise[] = [
  {
    id: 'squat',
    name: 'Squat',
    nameTr: 'Squat',
    description: 'A compound lower body exercise targeting quads, glutes, and hamstrings.',
    descriptionTr: 'Quadriceps, kalça ve hamstring kaslarını hedefleyen temel alt vücut egzersizi.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes', 'hamstrings', 'core'],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: [
      'Keep your chest up and core engaged',
      'Push your knees out over your toes',
      'Go at least to parallel (90° knee bend)',
      'Keep weight on your heels',
    ],
    tipsTr: [
      'Göğsünüzü yukarıda ve core kaslarınızı aktif tutun',
      'Dizlerinizi ayak parmaklarınızın üzerine doğru itin',
      'Göğsünü dik, sırtını düz tut.',
      'Dizlerin parmak uçlarını geçmesin.',
      'Ağırlığı topuklarına vererek kalk.',
    ],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0043.gif'
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    nameTr: 'Deadlift',
    description: 'A posterior chain exercise focusing on back, glutes, and hamstrings.',
    descriptionTr: 'Sırt, kalça ve hamstring kaslarına odaklanan arka zincir egzersizi.',
    category: 'lower_body',
    difficulty: 'intermediate',
    muscleGroups: ['back', 'glutes', 'hamstrings', 'core'],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: [
      'Keep the bar close to your body',
      'Hinge at the hips, not the lower back',
      'Maintain a neutral spine throughout',
      'Drive through your heels',
    ],
    tipsTr: [
      'Barı vücudunuza yakın tutun',
      'Belden değil, kalçalardan bükülün',
      'Omurganızı nötr pozisyonda tutun',
      'Topuklarınızdan itin',
    ],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0032.gif'
  },
  {
    id: 'pushup',
    name: 'Push-Up',
    nameTr: 'Şınav',
    description: 'A classic upper body exercise for chest, shoulders, and triceps.',
    descriptionTr: 'Göğüs, omuz ve triceps kasları için klasik üst vücut egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['chest', 'shoulders', 'arms', 'core'],
    icon: '🫸',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: [
      'Keep your body in a straight line',
      'Lower until elbows reach 90°',
      'Keep your core tight',
      'Don\'t let your hips sag',
    ],
    tipsTr: [
      'Vücudunuzu düz bir çizgide tutun',
      'Dirsekleriniz 90°ye ulaşana kadar inin',
      'Core kaslarınızı sıkı tutun',
      'Kalçalarınızın düşmesine izin vermeyin',
    ],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0662.gif'
  },
  {
    id: 'lunge',
    name: 'Lunge',
    nameTr: 'Lunge',
    description: 'A unilateral lower body exercise for balance and strength.',
    descriptionTr: 'Denge ve güç için tek taraflı alt vücut egzersizi.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes', 'hamstrings', 'calves'],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: [
      'Step far enough forward',
      'Keep your front knee over your ankle',
      'Lower your back knee toward the ground',
      'Keep your torso upright',
    ],
    tipsTr: [
      'Yeterince ileri adım atın',
      'Ön dizinizi bileğinizin üzerinde tutun',
      'Arka dizinizi yere doğru indirin',
      'Gövdenizi dik tutun',
    ],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0054.gif'
  },
  {
    id: 'plank',
    name: 'Plank',
    nameTr: 'Plank',
    description: 'An isometric core exercise for stability and endurance.',
    descriptionTr: 'Stabilite ve dayanıklılık için izometrik core egzersizi.',
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ['core', 'shoulders', 'back'],
    icon: '🧘',
    defaultSets: 3,
    defaultReps: 1,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: [
      'Keep your body in a straight line from head to heels',
      'Engage your core and glutes',
      'Don\'t let your hips drop or pike up',
      'Breathe steadily',
    ],
    tipsTr: [
      'Baştan topuklara düz bir çizgi oluşturun',
      'Core ve kalça kaslarınızı aktif edin',
      'Kalçalarınızın düşmesine veya yükselmesine izin vermeyin',
      'Düzenli nefes alın',
    ],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0464.gif'
  },

  // BICEPS (5)
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    nameTr: 'Halter Curl',
    description: 'A classic biceps builder using a barbell.',
    descriptionTr: 'Halter kullanarak yapılan klasik biceps egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep your elbows pinned to your sides', 'Do not swing your back', 'Squeeze at the top'],
    tipsTr: ['Dirseklerinizi gövdenize bitişik tutun', 'Sırtınızdan güç alarak sallanmayın', 'Tepe noktasında kasın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0031.gif'
  },
  {
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    nameTr: 'Dumbbell Curl',
    description: 'Biceps curl using dumbbells for unilateral balance.',
    descriptionTr: 'Denge ve izolasyon için dambıl ile yapılan biceps egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Supinate your wrist as you curl', 'Control the eccentric phase', 'Keep posture straight'],
    tipsTr: ['Kaldırırken bileğinizi dışa doğru çevirin', 'İndiriş aşamasını yavaş yapın', 'Dik duruşunuzu bozmayın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0285.gif'
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    nameTr: 'Hammer Curl',
    description: 'Targets the brachialis and brachioradialis.',
    descriptionTr: 'Biceps\'in alt kısımlarını ve ön kolu hedefler.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '🔨',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep a neutral grip', 'Do not let shoulders roll forward', 'Squeeze forearms'],
    tipsTr: ['Nötr (çekiç) tutuşunu koruyun', 'Omuzlarınızın öne düşmesine izin vermeyin', 'Ön kolları kasın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0313.gif'
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    nameTr: 'Preacher Curl',
    description: 'Isolates the biceps by resting the triceps on a pad.',
    descriptionTr: 'Kolları bir sehpaya dayayarak bicepsi izole eden egzersiz.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['arms'],
    icon: '🦾',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep armpits tight against the pad', 'Full extension at the bottom', 'Do not use momentum'],
    tipsTr: ['Koltuk altlarınızı sehpaya tam yaslayın', 'Altta kolunuzu tam açın', 'İvme kullanmayın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0452.gif'
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    nameTr: 'Konsantrasyon Curl',
    description: 'A strict isolation exercise for the biceps peak.',
    descriptionTr: 'Biceps tepe noktasını hedefleyen izole egzersiz.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['arms'],
    icon: '🎯',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 45,
    cameraPosition: 'front',
    tips: ['Rest elbow on inner thigh', 'Control the weight', 'Focus on the mind-muscle connection'],
    tipsTr: ['Dirseğinizi iç bacağınıza yaslayın', 'Ağırlığı kontrol edin', 'Kas-zihin bağlantısına odaklanın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0297.gif'
  },

  // TRICEPS (5)
  {
    id: 'tricep_extension',
    name: 'Tricep Extension',
    nameTr: 'Triceps Extension',
    description: 'An overhead extension targeting the long head of the triceps.',
    descriptionTr: 'Triceps uzun başını hedefleyen baş üstü uzatma egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['arms'],
    icon: '⚡',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep elbows pointing up', 'Core tight', 'Full stretch at the bottom'],
    tipsTr: ['Dirsekler yukarı baksın', 'Karın kaslarınızı sıkı tutun', 'Altta tam esneme sağlayın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0362.gif'
  },
  {
    id: 'skullcrusher',
    name: 'Skullcrusher',
    nameTr: 'Alna Triceps (Skullcrusher)',
    description: 'Lying triceps extension with an EZ bar or dumbbells.',
    descriptionTr: 'Yatarak yapılan triceps izole egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['arms'],
    icon: '💀',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Keep upper arms stationary', 'Lower bar to forehead', 'Press back up forcefully'],
    tipsTr: ['Üst kolları sabit tutun', 'Barı alnınıza doğru indirin', 'Güçlü bir şekilde yukarı itin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0337.gif'
  },
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    nameTr: 'Triceps Pushdown',
    description: 'Cable pushdown for triceps isolation.',
    descriptionTr: 'Kablo ile yapılan triceps itiş egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '⬇️',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: ['Keep elbows tucked', 'Stand straight', 'Lock out at the bottom'],
    tipsTr: ['Dirsekleri gövdeye yapışık tutun', 'Dik durun', 'En altta kolları tam kilitleyin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0201.gif'
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Cable Extension',
    nameTr: 'Kablo Baş Üstü Triceps',
    description: 'Cable variation of the overhead extension.',
    descriptionTr: 'Baş üstü triceps uzatmasının kablo varyasyonu.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['arms'],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Lean forward slightly', 'Keep elbows fixed', 'Squeeze triceps at extension'],
    tipsTr: ['Hafifçe öne eğilin', 'Dirsekleri sabit tutun', 'Uzatma anında kası sıkın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0194.gif'
  },
  {
    id: 'close_grip_bench',
    name: 'Close Grip Bench',
    nameTr: 'Dar Tutuş Bench Press',
    description: 'Compound movement emphasizing the triceps and inner chest.',
    descriptionTr: 'Triceps ve iç göğüs ağırlıklı bileşik pres egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'arms'],
    icon: '🛏️',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Grip shoulder-width apart', 'Keep elbows tucked', 'Lower to lower chest'],
    tipsTr: ['Omuz genişliğinde tutun', 'Dirsekleri içeri alın', 'Alt göğse doğru indirin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0030.gif'
  },

  // CHEST (5)
  {
    id: 'bench_press',
    name: 'Bench Press',
    nameTr: 'Bench Press',
    description: 'Primary compound exercise for chest development.',
    descriptionTr: 'Göğüs gelişimi için temel itiş egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    icon: '🏋️',
    defaultSets: 4,
    defaultReps: 8,
    restSeconds: 120,
    cameraPosition: 'side',
    tips: ['Retract scapula', 'Plant feet firmly', 'Touch mid-chest'],
    tipsTr: ['Kürek kemiklerini sıkıştırın', 'Ayakları yere sağlam basın', 'Orta göğse temas edin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0025.gif'
  },
  {
    id: 'incline_bench_press',
    name: 'Incline Bench Press',
    nameTr: 'Üst Göğüs Press',
    description: 'Targets the upper pectorals.',
    descriptionTr: 'Üst göğüs kaslarını hedefler.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    icon: '↗️',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Set bench to 30-45 degrees', 'Don\'t bounce the bar', 'Full range of motion'],
    tipsTr: ['Sehpayı 30-45 dereceye ayarlayın', 'Barı göğsünüzde zıplatmayın', 'Tam hareket açıklığını kullanın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0047.gif'
  },
  {
    id: 'dumbbell_fly',
    name: 'Dumbbell Fly',
    nameTr: 'Dumbbell Fly',
    description: 'Isolation exercise to stretch and contract the chest.',
    descriptionTr: 'Göğsü esnetip sıkıştıran izolasyon egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest'],
    icon: '🦅',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Keep a slight bend in elbows', 'Feel the stretch', 'Hug a tree motion'],
    tipsTr: ['Dirsekleri hafif bükük tutun', 'Esnemeyi hissedin', 'Ağaca sarılma hareketi yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0308.gif'
  },
  {
    id: 'chest_dip',
    name: 'Chest Dip',
    nameTr: 'Göğüs Dips',
    description: 'Bodyweight compound for lower chest and triceps.',
    descriptionTr: 'Alt göğüs ve triceps için vücut ağırlığı egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    icon: '🤸',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Lean forward', 'Flared elbows slightly', 'Go down until 90 degrees'],
    tipsTr: ['Öne doğru eğilin', 'Dirsekleri hafifçe dışa açın', '90 derece olana kadar inin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0251.gif'
  },
  {
    id: 'cable_crossover',
    name: 'Cable Crossover',
    nameTr: 'Cable Crossover',
    description: 'Constant tension isolation for the inner chest.',
    descriptionTr: 'İç göğüs için sürekli gerilim sağlayan kablo egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest'],
    icon: '✖️',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Stagger your stance', 'Keep chest proud', 'Cross hands slightly at the end'],
    tipsTr: ['Bir ayağınızı öne alın', 'Göğsünüzü dışarı çıkarın', 'Hareketi bitirirken ellerinizi çaprazlayın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0155.gif'
  },

  // SHOULDERS (5)
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    nameTr: 'Omuz Press',
    description: 'Standing or seated compound press for deltoids.',
    descriptionTr: 'Omuz kasları için ayakta veya oturarak itiş egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['shoulders', 'arms', 'core'],
    icon: '⬆️',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Brace your core', 'Press in a straight line', 'Don\'t overarch your lower back'],
    tipsTr: ['Karın kaslarınızı sıkın', 'Düz bir çizgide itin', 'Belinizi gereğinden fazla çukurlatmayın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0426.gif'
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    nameTr: 'Yana Açış',
    description: 'Isolates the lateral/side deltoids for shoulder width.',
    descriptionTr: 'Omuz genişliği için yan omuz kaslarını izole eder.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['shoulders'],
    icon: '↔️',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Lead with the elbows', 'Slight bend in arms', 'Don\'t use momentum'],
    tipsTr: ['Harekete dirseklerinizle öncülük edin', 'Kolları hafif bükük tutun', 'Sallanarak ivme almayın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0334.gif'
  },
  {
    id: 'front_raise',
    name: 'Front Raise',
    nameTr: 'Öne Açış',
    description: 'Targets the anterior/front deltoids.',
    descriptionTr: 'Ön omuz kaslarını hedefler.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['shoulders'],
    icon: '🧟',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Raise to eye level', 'Control the descent', 'Keep torso still'],
    tipsTr: ['Göz hizasına kadar kaldırın', 'İndirişi yavaş yapın', 'Gövdenizi sabit tutun'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0310.gif'
  },
  {
    id: 'upright_row',
    name: 'Upright Row',
    nameTr: 'Upright Row',
    description: 'Engages side deltoids and traps.',
    descriptionTr: 'Yan omuz ve trapez kaslarını çalıştırır.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['shoulders', 'back'],
    icon: '⏫',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Pull with elbows high', 'Keep bar close to body', 'Stop at chest level'],
    tipsTr: ['Dirsekleri yukarı doğru çekin', 'Barı vücuda yakın tutun', 'Göğüs hizasında durun'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0119.gif'
  },
  {
    id: 'reverse_pec_deck',
    name: 'Reverse Pec Deck',
    nameTr: 'Arka Omuz Makinesi',
    description: 'Isolates the rear deltoids using a machine.',
    descriptionTr: 'Makine kullanarak arka omuz kaslarını izole eder.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['shoulders', 'back'],
    icon: '🦋',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: ['Keep arms parallel to floor', 'Squeeze shoulder blades', 'Controlled movements'],
    tipsTr: ['Kolları yere paralel tutun', 'Kürek kemiklerini sıkıştırın', 'Kontrollü hareket edin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0154.gif'
  },

  // BACK (5)
  {
    id: 'pull_up',
    name: 'Pull Up',
    nameTr: 'Barfiks',
    description: 'The ultimate bodyweight back builder.',
    descriptionTr: 'Temel vücut ağırlığı sırt egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['back', 'arms', 'core'],
    icon: '🦍',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Pull chest to bar', 'Engage lats first', 'Full extension at bottom'],
    tipsTr: ['Göğsünüzü bara doğru çekin', 'Önce kanat kaslarınızı kasın', 'En altta tam esneyin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0651.gif'
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    nameTr: 'Lat Pulldown',
    description: 'Machine alternative to pull ups for lats.',
    descriptionTr: 'Kanat kasları için makine egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['back', 'arms'],
    icon: '⬇️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Lean back slightly', 'Pull to upper chest', 'Squeeze back at the bottom'],
    tipsTr: ['Hafifçe geriye yaslanın', 'Üst göğse doğru çekin', 'En altta sırtınızı sıkın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/2330.gif'
  },
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    nameTr: 'Barbell Row',
    description: 'Heavy compound row for back thickness.',
    descriptionTr: 'Sırt kalınlığı için ağır bileşik çekiş.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['back', 'arms', 'core'],
    icon: '🚣',
    defaultSets: 4,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Keep back parallel to floor', 'Pull to belly button', 'Maintain neutral spine'],
    tipsTr: ['Sırtınızı yere paralel tutun', 'Göbek deliğinize doğru çekin', 'Omurganızı düz tutun'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0027.gif'
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    nameTr: 'Oturarak Kablo Çekiş',
    description: 'Machine row for mid-back and lats.',
    descriptionTr: 'Orta sırt ve kanatlar için oturarak çekiş.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['back', 'arms'],
    icon: '🚠',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep chest up', 'Do not rock back and forth', 'Squeeze shoulder blades together'],
    tipsTr: ['Göğsünüzü dik tutun', 'İleri geri sallanmayın', 'Kürek kemiklerini birbirine yaklaştırın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0861.gif'
  },
  {
    id: 't_bar_row',
    name: 'T-Bar Row',
    nameTr: 'T-Bar Row',
    description: 'A close-grip heavy rowing exercise.',
    descriptionTr: 'Dar tutuşlu ağır sırt çekiş egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['back', 'arms', 'core'],
    icon: '⚔️',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Straddle the bar', 'Keep lower back tight', 'Use V-grip handle'],
    tipsTr: ['Barı bacaklarınızın arasına alın', 'Belinizi sıkı tutun', 'V-tutamak kullanın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1349.gif'
  },
  {
    id: 'walking',
    name: 'Walking',
    nameTr: 'Yürüyüş',
    description: 'Basic walking locomotion to track steps and posture.',
    descriptionTr: 'Adım saymak ve duruşu takip etmek için temel yürüyüş.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'hamstrings', 'core'],
    icon: '🚶',
    defaultSets: 1,
    defaultReps: 100, // Represents steps for walking
    restSeconds: 0,
    cameraPosition: 'side',
    tips: ['Keep your chest up', 'Maintain a neutral spine', 'Swing arms naturally'],
    tipsTr: ['Göğsünüzü dik tutun', 'Omurganızı düz tutun', 'Kollarınızı doğal sallayın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/3666.gif'
  },
  // PILATES
  {
    id: 'pilates_hundred',
    name: 'Pilates Hundred',
    nameTr: 'Pilates Hundred',
    description: 'A classic Pilates mat exercise for core strength.',
    descriptionTr: 'Karın bölgesini güçlendiren klasik bir Pilates mat egzersizi.',
    category: 'pilates',
    difficulty: 'beginner',
    muscleGroups: ['core'],
    icon: '🧘',
    defaultSets: 1,
    defaultReps: 100,
    restSeconds: 30,
    cameraPosition: 'side',
    tips: ['Keep your lower back pressed to the mat', 'Pump your arms vigorously', 'Breathe in for 5, out for 5'],
    tipsTr: ['Belinizi mata bastırın', 'Kollarınızı omuzdan ritmik şekilde pompalayın', '5 sayıda nefes al, 5 sayıda ver'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0274.gif'
  },
  {
    id: 'pilates_roll_up',
    name: 'Pilates Roll Up',
    nameTr: 'Pilates Roll Up',
    description: 'Articulates the spine and strengthens the abdominals.',
    descriptionTr: 'Omurgayı esneten ve karın kaslarını güçlendiren bir hareket.',
    category: 'pilates',
    difficulty: 'intermediate',
    muscleGroups: ['core'],
    icon: '🧘',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: ['Peel your spine off the mat one vertebra at a time', 'Keep legs straight and together', 'Use your core, not momentum'],
    tipsTr: ['Omurganızı yavaşça tek tek mattan ayırın', 'Bacaklarınızı düz ve bitişik tutun', 'Hızlanmadan, karın kaslarınızla kalkın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0001.gif'
  },
  {
    id: 'pilates_bridge',
    name: 'Pilates Bridge',
    nameTr: 'Pilates Köprü',
    description: 'Improves hip mobility and glute strength.',
    descriptionTr: 'Kalça mobilitesini ve glute gücünü artırır.',
    category: 'pilates',
    difficulty: 'beginner',
    muscleGroups: ['glutes', 'core'],
    icon: '🧘',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 30,
    cameraPosition: 'side',
    tips: ['Tuck your pelvis and roll up', 'Squeeze glutes at the top', 'Roll down smoothly'],
    tipsTr: ['Kalçanızı sıkarak yavaşça yukarı kalkın', 'Tepe noktasında kalçanızı sıkın', 'Omurganızı tek tek yere indirin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1409.gif'
  },
  {
    id: 'pilates_scissors',
    name: 'Pilates Scissors',
    nameTr: 'Pilates Makas',
    description: 'Core exercise where legs move in a scissor-like motion.',
    descriptionTr: 'Bacakların havada ileri geri makas gibi hareket ettirildiği karın egzersizi.',
    category: 'pilates',
    difficulty: 'intermediate',
    muscleGroups: ['core', 'quads'],
    icon: '✂️',
    defaultSets: 3,
    defaultReps: 20,
    restSeconds: 30,
    cameraPosition: 'side',
    tips: ['Keep your lower back glued to the mat', 'Keep your legs straight', 'Engage your core constantly'],
    tipsTr: ['Belinizi sürekli mata yapışık tutun', 'Bacaklarınızı düz tutmaya çalışın', 'Karın kaslarınızı sürekli sıkı tutun'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0459.gif'
  },
  // NEW EXERCISES ADDED FROM USER REQUEST
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    nameTr: 'Kablo Fly',
    description: 'An isolation exercise for the chest providing constant tension.',
    descriptionTr: 'Göğüs için sürekli gerilim sağlayan izolasyon egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest'],
    icon: '🦅',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Keep a slight bend in your elbows', 'Squeeze your chest at the center', 'Control the eccentric phase'],
    tipsTr: ['Dirseklerinizde hafif bir bükülme koruyun', 'Ortada göğsünüzü sıkıştırın', 'Negatif aşamayı kontrol edin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0155.gif'
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    nameTr: 'Üst Göğüs Dumbbell Press',
    description: 'Targets the upper pectorals and provides a deep stretch.',
    descriptionTr: 'Üst göğüs kaslarını hedefler ve derin bir esneme sağlar.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    icon: '↗️',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Set bench to 30-45 degrees', 'Press the dumbbells straight up', 'Lower until you feel a stretch'],
    tipsTr: ['Sehpayı 30-45 dereceye ayarlayın', 'Dambılları düz bir şekilde yukarı itin', 'Esnemeyi hissedene kadar indirin'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0314.gif'
  },
  {
    id: 'chest_supported_row',
    name: 'Chest Supported Row',
    nameTr: 'Göğüs Destekli Row',
    description: 'A rowing variation that isolates the back by eliminating momentum.',
    descriptionTr: 'İvmeyi ortadan kaldırarak sırtı izole eden bir row varyasyonu.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['back', 'arms'],
    icon: '🛶',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep your chest glued to the pad', 'Pull with your elbows', 'Squeeze shoulder blades together'],
    tipsTr: ['Göğsünüzü sehpaya yapışık tutun', 'Dirseklerinizle çekin', 'Kürek kemiklerinizi birbirine yaklaştırın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0293.gif'
  },
  {
    id: 'face_pull',
    name: 'Cable Face Pull',
    nameTr: 'Kablo Face Pull',
    description: 'Targets rear deltoids and rotator cuff for shoulder health.',
    descriptionTr: 'Omuz sağlığı için arka omuz ve rotator manşet kaslarını hedefler.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['shoulders', 'back'],
    icon: '🪢',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Pull the rope towards your face', 'Keep elbows high and wide', 'Externally rotate at the end'],
    tipsTr: ['Halatı yüzünüze doğru çekin', 'Dirseklerinizi yüksek ve geniş tutun', 'Hareket sonunda dışa rotasyon yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0203.gif'
  },
  {
    id: 'bayesian_curl',
    name: 'Bayesian Curl',
    nameTr: 'Bayesian Curl',
    description: 'A cable curl variation that emphasizes the stretch position of the biceps.',
    descriptionTr: 'Biceps\'in esneme pozisyonunu vurgulayan bir kablo curl varyasyonu.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['arms'],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Face away from the cable machine', 'Keep your elbow behind your torso', 'Curl forward and up'],
    tipsTr: ['Kablo makinesine arkanızı dönün', 'Dirseğinizi gövdenizin arkasında tutun', 'İleri ve yukarı doğru curl yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0868.gif'
  },
  {
    id: 'wrist_extension',
    name: 'Wrist Extension',
    nameTr: 'Bilek Ekstansiyonu',
    description: 'Isolates the forearm extensors.',
    descriptionTr: 'Ön kol ekstansör kaslarını izole eder.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '✋',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: ['Rest your forearm on a bench', 'Use a light weight', 'Curl the wrist upward'],
    tipsTr: ['Ön kolunuzu sehpaya dayayın', 'Hafif bir ağırlık kullanın', 'Bileğinizi yukarı doğru bükün'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0079.gif'
  },
  {
    id: 'wrist_supination',
    name: 'Wrist Supination',
    nameTr: 'Bilek Supinasyonu',
    description: 'Strengthens the supinator muscle of the forearm.',
    descriptionTr: 'Ön kolun supinatör kasını güçlendirir.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '🔄',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: ['Hold a dumbbell on one side', 'Rotate your wrist outward', 'Control the movement'],
    tipsTr: ['Dambılı tek tarafından tutun', 'Bileğinizi dışa doğru çevirin', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1016.gif'
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    nameTr: 'Leg Press',
    description: 'Alt vücut için makine egzersizi.',
    descriptionTr: 'Alt vücut için makine egzersizi.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ["quads", "glutes", "hamstrings"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0739.gif'
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    nameTr: 'Bulgarian Split Squat',
    description: 'Tek bacak odaklı zorlu bir egzersiz.',
    descriptionTr: 'Tek bacak odaklı zorlu bir egzersiz.',
    category: 'lower_body',
    difficulty: 'advanced',
    muscleGroups: ["quads", "glutes"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0410.gif'
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlift',
    nameTr: 'Rumen Deadlift',
    description: 'Arka bacak ve kalça odaklı deadlift.',
    descriptionTr: 'Arka bacak ve kalça odaklı deadlift.',
    category: 'lower_body',
    difficulty: 'intermediate',
    muscleGroups: ["hamstrings", "glutes", "back"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0085.gif'
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    nameTr: 'Bacak Uzatma',
    description: 'Ön bacak kaslarını izole eder.',
    descriptionTr: 'Ön bacak kaslarını izole eder.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ["quads"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0585.gif'
  },
  {
    id: 'lying_leg_curl',
    name: 'Lying Leg Curl',
    nameTr: 'Yatarak Bacak Bükme',
    description: 'Arka bacak kaslarını izole eder.',
    descriptionTr: 'Arka bacak kaslarını izole eder.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ["hamstrings"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0586.gif'
  },
  {
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    nameTr: 'Oturarak Bacak Bükme',
    description: 'Arka bacak kaslarını oturarak izole eder.',
    descriptionTr: 'Arka bacak kaslarını oturarak izole eder.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ["hamstrings"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0599.gif'
  },
  {
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    nameTr: 'Ayakta Kalf Kaldırma',
    description: 'Baldır kaslarını çalıştırır.',
    descriptionTr: 'Baldır kaslarını çalıştırır.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ["calves"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1372.gif'
  },
  {
    id: 'seated_calf_raise',
    name: 'Seated Calf Raise',
    nameTr: 'Oturarak Kalf Kaldırma',
    description: 'Soleus baldır kasına odaklanır.',
    descriptionTr: 'Soleus baldır kasına odaklanır.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ["calves"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1371.gif'
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    nameTr: 'Kalça İtiş',
    description: 'Kalça kasları için en etkili hareketlerden biri.',
    descriptionTr: 'Kalça kasları için en etkili hareketlerden biri.',
    category: 'lower_body',
    difficulty: 'intermediate',
    muscleGroups: ["glutes", "hamstrings"],
    icon: '🍑',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1409.gif'
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    nameTr: 'Goblet Squat',
    description: 'Dambıl ile yapılan ön squat varyasyonu.',
    descriptionTr: 'Dambıl ile yapılan ön squat varyasyonu.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ["quads", "glutes", "core"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1760.gif'
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    nameTr: 'Hack Squat',
    description: 'Makine ile yapılan güvenli squat.',
    descriptionTr: 'Makine ile yapılan güvenli squat.',
    category: 'lower_body',
    difficulty: 'intermediate',
    muscleGroups: ["quads", "glutes"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0743.gif'
  },
  {
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    nameTr: 'Sumo Deadlift',
    description: 'Geniş duruşlu deadlift.',
    descriptionTr: 'Geniş duruşlu deadlift.',
    category: 'lower_body',
    difficulty: 'intermediate',
    muscleGroups: ["glutes", "hamstrings", "back"],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0117.gif'
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    nameTr: 'Ön Squat',
    description: 'Halteri önde tutarak yapılan squat.',
    descriptionTr: 'Halteri önde tutarak yapılan squat.',
    category: 'lower_body',
    difficulty: 'advanced',
    muscleGroups: ["quads", "core", "back"],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0042.gif'
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    nameTr: 'Chin-Up',
    description: 'Avuç içleri size dönük barfiks.',
    descriptionTr: 'Avuç içleri size dönük barfiks.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ["back", "arms"],
    icon: '🦍',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1326.gif'
  },
  {
    id: 'dumbbell_row',
    name: 'Dumbbell Row',
    nameTr: 'Dambıl Row',
    description: 'Tek kolla yapılan sırt egzersizi.',
    descriptionTr: 'Tek kolla yapılan sırt egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["back", "arms"],
    icon: '🚣',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0293.gif'
  },
  {
    id: 'pendlay_row',
    name: 'Pendlay Row',
    nameTr: 'Pendlay Row',
    description: 'Yerden her seferinde baştan çekilen row.',
    descriptionTr: 'Yerden her seferinde baştan çekilen row.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ["back", "core"],
    icon: '🚣',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0027.gif'
  },
  {
    id: 'straight_arm_pulldown',
    name: 'Straight Arm Pulldown',
    nameTr: 'Düz Kol Pulldown',
    description: 'Kanat kaslarını izole eden hareket.',
    descriptionTr: 'Kanat kaslarını izole eden hareket.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["back"],
    icon: '🦍',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0238.gif'
  },
  {
    id: 'shrugs',
    name: 'Shrugs',
    nameTr: 'Omuz Silkme (Shrug)',
    description: 'Trapez kaslarını geliştirir.',
    descriptionTr: 'Trapez kaslarını geliştirir.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["back", "shoulders"],
    icon: '🦍',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0095.gif'
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    nameTr: 'Good Morning',
    description: 'Alt sırt ve arka bacak egzersizi.',
    descriptionTr: 'Alt sırt ve arka bacak egzersizi.',
    category: 'lower_body',
    difficulty: 'intermediate',
    muscleGroups: ["back", "hamstrings"],
    icon: '🦵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0044.gif'
  },
  {
    id: 'hyperextension',
    name: 'Hyperextension',
    nameTr: 'Ters Mekik',
    description: 'Alt sırt (bel) kaslarını güçlendirir.',
    descriptionTr: 'Alt sırt (bel) kaslarını güçlendirir.',
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ["back", "core"],
    icon: '🧱',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0489.gif'
  },
  {
    id: 'decline_bench_press',
    name: 'Decline Bench Press',
    nameTr: 'Decline Bench Press',
    description: 'Alt göğüs kaslarını hedefler.',
    descriptionTr: 'Alt göğüs kaslarını hedefler.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ["chest", "arms", "shoulders"],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0033.gif'
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck Fly',
    nameTr: 'Kelebek (Pec Deck)',
    description: 'Göğüs kaslarını makinede izole eder.',
    descriptionTr: 'Göğüs kaslarını makinede izole eder.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["chest"],
    icon: '🛡️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0576.gif'
  },
  {
    id: 'dumbbell_pullover',
    name: 'Dumbbell Pullover',
    nameTr: 'Dambıl Pullover',
    description: 'Göğüs ve kanat kaslarını esneterek çalıştırır.',
    descriptionTr: 'Göğüs ve kanat kaslarını esneterek çalıştırır.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ["chest", "back"],
    icon: '🛡️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0375.gif'
  },
  {
    id: 'incline_dumbbell_fly',
    name: 'Incline Dumbbell Fly',
    nameTr: 'Eğimli Dambıl Fly',
    description: 'Üst göğüs kaslarını esnetir.',
    descriptionTr: 'Üst göğüs kaslarını esnetir.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ["chest"],
    icon: '🛡️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0319.gif'
  },
  {
    id: 'machine_chest_press',
    name: 'Machine Chest Press',
    nameTr: 'Makine Göğüs İtiş',
    description: 'Göğüs için güvenli makine egzersizi.',
    descriptionTr: 'Göğüs için güvenli makine egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["chest", "arms", "shoulders"],
    icon: '🛡️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0576.gif'
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    nameTr: 'Arnold Press',
    description: 'Omuz kaslarının tüm başlarını çalıştırır.',
    descriptionTr: 'Omuz kaslarının tüm başlarını çalıştırır.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ["shoulders", "arms"],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/2137.gif'
  },
  {
    id: 'seated_dumbbell_press',
    name: 'Seated Dumbbell Press',
    nameTr: 'Oturarak Dambıl İtiş',
    description: 'Oturarak yapılan temel omuz egzersizi.',
    descriptionTr: 'Oturarak yapılan temel omuz egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["shoulders", "arms"],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0405.gif'
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    nameTr: 'Kablo Yana Açış',
    description: 'Omuz yan başlarını kablo ile izole eder.',
    descriptionTr: 'Omuz yan başlarını kablo ile izole eder.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ["shoulders"],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0178.gif'
  },
  {
    id: 'front_dumbbell_raise',
    name: 'Front Dumbbell Raise',
    nameTr: 'Dambıl Öne Açış',
    description: 'Omuz ön başlarını çalıştırır.',
    descriptionTr: 'Omuz ön başlarını çalıştırır.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["shoulders"],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0310.gif'
  },
  {
    id: 'military_press',
    name: 'Military Press',
    nameTr: 'Askeri Pres',
    description: 'Ayakta halter ile omuz presi.',
    descriptionTr: 'Ayakta halter ile omuz presi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ["shoulders", "core", "arms"],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1456.gif'
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    nameTr: 'Arka Omuz Açış',
    description: 'Arka omuz kaslarını çalıştırır.',
    descriptionTr: 'Arka omuz kaslarını çalıştırır.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["shoulders", "back"],
    icon: '🦅',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0380.gif'
  },
  {
    id: 'spider_curl',
    name: 'Spider Curl',
    nameTr: 'Örümcek Curl',
    description: 'Eğimli sehpada yüzüstü biceps egzersizi.',
    descriptionTr: 'Eğimli sehpada yüzüstü biceps egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ["arms"],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1628.gif'
  },
  {
    id: 'ez_bar_curl',
    name: 'EZ Bar Curl',
    nameTr: 'Z Bar Curl',
    description: 'Bilekleri koruyan Z bar biceps curl.',
    descriptionTr: 'Bilekleri koruyan Z bar biceps curl.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["arms"],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0447.gif'
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    nameTr: 'Kablo Curl',
    description: 'Sürekli gerilim sağlayan kablo biceps.',
    descriptionTr: 'Sürekli gerilim sağlayan kablo biceps.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["arms"],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0868.gif'
  },
  {
    id: 'reverse_curl',
    name: 'Reverse Curl',
    nameTr: 'Ters Tutuş Curl',
    description: 'Ön kol ve bicepsi beraber çalıştırır.',
    descriptionTr: 'Ön kol ve bicepsi beraber çalıştırır.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ["arms"],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0080.gif'
  },
  {
    id: 'rope_pushdown',
    name: 'Rope Pushdown',
    nameTr: 'Halat Pushdown',
    description: 'Halat ile triceps itişi.',
    descriptionTr: 'Halat ile triceps itişi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["arms"],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0200.gif'
  },
  {
    id: 'overhead_dumbbell_extension',
    name: 'Overhead DB Extension',
    nameTr: 'Baş Üstü Dambıl Triceps',
    description: 'Dambıl ile baş üstü triceps uzatma.',
    descriptionTr: 'Dambıl ile baş üstü triceps uzatma.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["arms"],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0430.gif'
  },
  {
    id: 'tricep_kickback',
    name: 'Tricep Kickback',
    nameTr: 'Triceps Kickback',
    description: 'Dambıl ile geriye itiş triceps hareketi.',
    descriptionTr: 'Dambıl ile geriye itiş triceps hareketi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["arms"],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0333.gif'
  },
  {
    id: 'bench_dips',
    name: 'Bench Dips',
    nameTr: 'Sehpa Dips',
    description: 'Vücut ağırlığı ile arka kol egzersizi.',
    descriptionTr: 'Vücut ağırlığı ile arka kol egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["arms", "chest"],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0129.gif'
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    nameTr: 'Russian Twist',
    description: 'Karın yan kaslarını (oblikleri) çalıştırır.',
    descriptionTr: 'Karın yan kaslarını (oblikleri) çalıştırır.',
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ["core"],
    icon: '🧱',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0687.gif'
  },
  {
    id: 'leg_raises',
    name: 'Leg Raises',
    nameTr: 'Yatarak Bacak Kaldırma',
    description: 'Alt karın kaslarını hedefler.',
    descriptionTr: 'Alt karın kaslarını hedefler.',
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ["core"],
    icon: '🧱',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0472.gif'
  },
  {
    id: 'bicycle_crunches',
    name: 'Bicycle Crunches',
    nameTr: 'Bisiklet Mekik',
    description: 'Tüm karın bölgesini aktif eden dinamik egzersiz.',
    descriptionTr: 'Tüm karın bölgesini aktif eden dinamik egzersiz.',
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ["core"],
    icon: '🧱',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0003.gif'
  },
  {
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    nameTr: 'Dağ Tırmanışı',
    description: 'Kardiyo ve core antrenmanı bir arada.',
    descriptionTr: 'Kardiyo ve core antrenmanı bir arada.',
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ["core"],
    icon: '🏃',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0630.gif'
  },
  {
    id: 'ab_roller',
    name: 'Ab Roller',
    nameTr: 'Tekerlek ile Karın',
    description: 'Tekerlek kullanarak zorlu karın egzersizi.',
    descriptionTr: 'Tekerlek kullanarak zorlu karın egzersizi.',
    category: 'core',
    difficulty: 'advanced',
    muscleGroups: ["core", "back"],
    icon: '🧱',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0103.gif'
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    nameTr: 'Asılı Bacak Kaldırma',
    description: 'Bara asılı kalarak alt karın çalıştırma.',
    descriptionTr: 'Bara asılı kalarak alt karın çalıştırma.',
    category: 'core',
    difficulty: 'advanced',
    muscleGroups: ["core"],
    icon: '🧱',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0472.gif'
  },
  {
    id: 'v_ups',
    name: 'V-Ups',
    nameTr: 'V Mekik',
    description: 'V şeklinde kapanarak tüm karnı çalıştırır.',
    descriptionTr: 'V şeklinde kapanarak tüm karnı çalıştırır.',
    category: 'core',
    difficulty: 'intermediate',
    muscleGroups: ["core"],
    icon: '🧱',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1014.gif'
  },
  {
    id: 'flutter_kicks',
    name: 'Flutter Kicks',
    nameTr: 'Makas Hareketi',
    description: 'Alt karın ve kalça fleksörleri için makas.',
    descriptionTr: 'Alt karın ve kalça fleksörleri için makas.',
    category: 'core',
    difficulty: 'beginner',
    muscleGroups: ["core"],
    icon: '🧱',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0459.gif'
  },
  {
    id: 'burpees',
    name: 'Burpees',
    nameTr: 'Burpee',
    description: 'Tüm vücut kondisyon hareketi.',
    descriptionTr: 'Tüm vücut kondisyon hareketi.',
    category: 'full_body',
    difficulty: 'intermediate',
    muscleGroups: ["core"],
    icon: '🥵',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/1160.gif'
  },
  {
    id: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    nameTr: 'Kettlebell Swing',
    description: 'Kalça patlayıcılığı ve kondisyon.',
    descriptionTr: 'Kalça patlayıcılığı ve kondisyon.',
    category: 'full_body',
    difficulty: 'intermediate',
    muscleGroups: ["glutes"],
    icon: '🏃',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep form strict', 'Breathe continuously', 'Control the movement'],
    tipsTr: ['Formunuzu bozmayın', 'Düzenli nefes alın', 'Hareketi kontrollü yapın'],
    demoUrl: 'https://raw.githubusercontent.com/omercotkd/exercises-gifs/main/assets/0549.gif'
  },
  {
    id: 'plate_hold',
    name: 'Plate Hold',
    nameTr: 'Plaka Tutma',
    description: 'Grip strength exercise holding a weight plate for time.',
    descriptionTr: 'Kavrama gücü için plaka tutma egzersizi (süreye karşı).',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ["forearms"],
    icon: '🤲',
    defaultSets: 3,
    defaultReps: 30,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Grip the plate firmly', 'Keep shoulders back', 'Breathe steadily'],
    tipsTr: ['Plakayı sıkıca kavrayın', 'Omuzları geriye çekin', 'Düzenli nefes alın'],
    demoUrl: ''
  },
];

export const CATEGORY_LABELS: Record<ExerciseCategory, { en: string; tr: string }> = {
  lower_body: { en: 'Lower Body', tr: 'Alt Vücut' },
  upper_body: { en: 'Upper Body', tr: 'Üst Vücut' },
  core: { en: 'Core', tr: 'Core' },
  full_body: { en: 'Full Body', tr: 'Tüm Vücut' },
  pilates: { en: 'Pilates', tr: 'Pilates' },
};

export const DIFFICULTY_LABELS: Record<Difficulty, { en: string; tr: string; color: string }> = {
  beginner: { en: 'Beginner', tr: 'Başlangıç', color: '#39FF14' },
  intermediate: { en: 'Intermediate', tr: 'Orta', color: '#FFE500' },
  advanced: { en: 'Advanced', tr: 'İleri', color: '#FF3131' },
};
