import { Exercise } from './exercises';

export const NEW_EXERCISES: Exercise[] = [
  // BICEPS (5)
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    nameTr: 'Halter Curl',
    description: 'A classic biceps builder using a barbell.',
    descriptionTr: 'Halter kullanarak yapılan klasik biceps egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep your elbows pinned to your sides', 'Do not swing your back', 'Squeeze at the top'],
    tipsTr: ['Dirseklerinizi gövdenize bitişik tutun', 'Sırtınızdan güç alarak sallanmayın', 'Tepe noktasında kasın'],
  },
  {
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    nameTr: 'Dumbbell Curl',
    description: 'Biceps curl using dumbbells for unilateral balance.',
    descriptionTr: 'Denge ve izolasyon için dambıl ile yapılan biceps egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '💪',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Supinate your wrist as you curl', 'Control the eccentric phase', 'Keep posture straight'],
    tipsTr: ['Kaldırırken bileğinizi dışa doğru çevirin', 'İndiriş aşamasını yavaş yapın', 'Dik duruşunuzu bozmayın'],
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    nameTr: 'Hammer Curl',
    description: 'Targets the brachialis and brachioradialis.',
    descriptionTr: 'Biceps\'in alt kısımlarını ve ön kolu hedefler.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '🔨',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep a neutral grip', 'Do not let shoulders roll forward', 'Squeeze forearms'],
    tipsTr: ['Nötr (çekiç) tutuşunu koruyun', 'Omuzlarınızın öne düşmesine izin vermeyin', 'Ön kolları kasın'],
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    nameTr: 'Preacher Curl',
    description: 'Isolates the biceps by resting the triceps on a pad.',
    descriptionTr: 'Kolları bir sehpaya dayayarak bicepsi izole eden egzersiz.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['arms'],
    icon: '🦾',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep armpits tight against the pad', 'Full extension at the bottom', 'Do not use momentum'],
    tipsTr: ['Koltuk altlarınızı sehpaya tam yaslayın', 'Altta kolunuzu tam açın', 'İvme kullanmayın'],
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    nameTr: 'Konsantrasyon Curl',
    description: 'A strict isolation exercise for the biceps peak.',
    descriptionTr: 'Biceps tepe noktasını hedefleyen izole egzersiz.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['arms'],
    icon: '🎯',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 45,
    cameraPosition: 'front',
    tips: ['Rest elbow on inner thigh', 'Control the weight', 'Focus on the mind-muscle connection'],
    tipsTr: ['Dirseğinizi iç bacağınıza yaslayın', 'Ağırlığı kontrol edin', 'Kas-zihin bağlantısına odaklanın'],
  },

  // TRICEPS (5)
  {
    id: 'tricep_extension',
    name: 'Tricep Extension',
    nameTr: 'Triceps Extension',
    description: 'An overhead extension targeting the long head of the triceps.',
    descriptionTr: 'Triceps uzun başını hedefleyen baş üstü uzatma egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['arms'],
    icon: '⚡',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep elbows pointing up', 'Core tight', 'Full stretch at the bottom'],
    tipsTr: ['Dirsekler yukarı baksın', 'Karın kaslarınızı sıkı tutun', 'Altta tam esneme sağlayın'],
  },
  {
    id: 'skullcrusher',
    name: 'Skullcrusher',
    nameTr: 'Alna Triceps (Skullcrusher)',
    description: 'Lying triceps extension with an EZ bar or dumbbells.',
    descriptionTr: 'Yatarak yapılan triceps izole egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['arms'],
    icon: '💀',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Keep upper arms stationary', 'Lower bar to forehead', 'Press back up forcefully'],
    tipsTr: ['Üst kolları sabit tutun', 'Barı alnınıza doğru indirin', 'Güçlü bir şekilde yukarı itin'],
  },
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    nameTr: 'Triceps Pushdown',
    description: 'Cable pushdown for triceps isolation.',
    descriptionTr: 'Kablo ile yapılan triceps itiş egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['arms'],
    icon: '⬇️',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: ['Keep elbows tucked', 'Stand straight', 'Lock out at the bottom'],
    tipsTr: ['Dirsekleri gövdeye yapışık tutun', 'Dik durun', 'En altta kolları tam kilitleyin'],
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Cable Extension',
    nameTr: 'Kablo Baş Üstü Triceps',
    description: 'Cable variation of the overhead extension.',
    descriptionTr: 'Baş üstü triceps uzatmasının kablo varyasyonu.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['arms'],
    icon: '🏋️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Lean forward slightly', 'Keep elbows fixed', 'Squeeze triceps at extension'],
    tipsTr: ['Hafifçe öne eğilin', 'Dirsekleri sabit tutun', 'Uzatma anında kası sıkın'],
  },
  {
    id: 'close_grip_bench',
    name: 'Close Grip Bench',
    nameTr: 'Dar Tutuş Bench Press',
    description: 'Compound movement emphasizing the triceps and inner chest.',
    descriptionTr: 'Triceps ve iç göğüs ağırlıklı bileşik pres egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'arms'],
    icon: '🛏️',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Grip shoulder-width apart', 'Keep elbows tucked', 'Lower to lower chest'],
    tipsTr: ['Omuz genişliğinde tutun', 'Dirsekleri içeri alın', 'Alt göğse doğru indirin'],
  },

  // CHEST (5)
  {
    id: 'bench_press',
    name: 'Bench Press',
    nameTr: 'Bench Press',
    description: 'Primary compound exercise for chest development.',
    descriptionTr: 'Göğüs gelişimi için temel itiş egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    icon: '🏋️',
    defaultSets: 4,
    defaultReps: 8,
    restSeconds: 120,
    cameraPosition: 'side',
    tips: ['Retract scapula', 'Plant feet firmly', 'Touch mid-chest'],
    tipsTr: ['Kürek kemiklerini sıkıştırın', 'Ayakları yere sağlam basın', 'Orta göğse temas edin'],
  },
  {
    id: 'incline_bench_press',
    name: 'Incline Bench Press',
    nameTr: 'Üst Göğüs Press',
    description: 'Targets the upper pectorals.',
    descriptionTr: 'Üst göğüs kaslarını hedefler.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    icon: '↗️',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Set bench to 30-45 degrees', 'Don\'t bounce the bar', 'Full range of motion'],
    tipsTr: ['Sehpayı 30-45 dereceye ayarlayın', 'Barı göğsünüzde zıplatmayın', 'Tam hareket açıklığını kullanın'],
  },
  {
    id: 'dumbbell_fly',
    name: 'Dumbbell Fly',
    nameTr: 'Dumbbell Fly',
    description: 'Isolation exercise to stretch and contract the chest.',
    descriptionTr: 'Göğsü esnetip sıkıştıran izolasyon egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest'],
    icon: '🦅',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Keep a slight bend in elbows', 'Feel the stretch', 'Hug a tree motion'],
    tipsTr: ['Dirsekleri hafif bükük tutun', 'Esnemeyi hissedin', 'Ağaca sarılma hareketi yapın'],
  },
  {
    id: 'chest_dip',
    name: 'Chest Dip',
    nameTr: 'Göğüs Dips',
    description: 'Bodyweight compound for lower chest and triceps.',
    descriptionTr: 'Alt göğüs ve triceps için vücut ağırlığı egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    icon: '🤸',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Lean forward', 'Flared elbows slightly', 'Go down until 90 degrees'],
    tipsTr: ['Öne doğru eğilin', 'Dirsekleri hafifçe dışa açın', '90 derece olana kadar inin'],
  },
  {
    id: 'cable_crossover',
    name: 'Cable Crossover',
    nameTr: 'Cable Crossover',
    description: 'Constant tension isolation for the inner chest.',
    descriptionTr: 'İç göğüs için sürekli gerilim sağlayan kablo egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['chest'],
    icon: '✖️',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Stagger your stance', 'Keep chest proud', 'Cross hands slightly at the end'],
    tipsTr: ['Bir ayağınızı öne alın', 'Göğsünüzü dışarı çıkarın', 'Hareketi bitirirken ellerinizi çaprazlayın'],
  },

  // SHOULDERS (5)
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    nameTr: 'Omuz Press',
    description: 'Standing or seated compound press for deltoids.',
    descriptionTr: 'Omuz kasları için ayakta veya oturarak itiş egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['shoulders', 'arms', 'core'],
    icon: '⬆️',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Brace your core', 'Press in a straight line', 'Don\'t overarch your lower back'],
    tipsTr: ['Karın kaslarınızı sıkın', 'Düz bir çizgide itin', 'Belinizi gereğinden fazla çukurlatmayın'],
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    nameTr: 'Yana Açış',
    description: 'Isolates the lateral/side deltoids for shoulder width.',
    descriptionTr: 'Omuz genişliği için yan omuz kaslarını izole eder.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['shoulders'],
    icon: '↔️',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Lead with the elbows', 'Slight bend in arms', 'Don\'t use momentum'],
    tipsTr: ['Harekete dirseklerinizle öncülük edin', 'Kolları hafif bükük tutun', 'Sallanarak ivme almayın'],
  },
  {
    id: 'front_raise',
    name: 'Front Raise',
    nameTr: 'Öne Açış',
    description: 'Targets the anterior/front deltoids.',
    descriptionTr: 'Ön omuz kaslarını hedefler.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['shoulders'],
    icon: '🧟',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Raise to eye level', 'Control the descent', 'Keep torso still'],
    tipsTr: ['Göz hizasına kadar kaldırın', 'İndirişi yavaş yapın', 'Gövdenizi sabit tutun'],
  },
  {
    id: 'upright_row',
    name: 'Upright Row',
    nameTr: 'Upright Row',
    description: 'Engages side deltoids and traps.',
    descriptionTr: 'Yan omuz ve trapez kaslarını çalıştırır.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['shoulders', 'back'],
    icon: '⏫',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 60,
    cameraPosition: 'front',
    tips: ['Pull with elbows high', 'Keep bar close to body', 'Stop at chest level'],
    tipsTr: ['Dirsekleri yukarı doğru çekin', 'Barı vücuda yakın tutun', 'Göğüs hizasında durun'],
  },
  {
    id: 'reverse_pec_deck',
    name: 'Reverse Pec Deck',
    nameTr: 'Arka Omuz Makinesi',
    description: 'Isolates the rear deltoids using a machine.',
    descriptionTr: 'Makine kullanarak arka omuz kaslarını izole eder.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['shoulders', 'back'],
    icon: '🦋',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: ['Keep arms parallel to floor', 'Squeeze shoulder blades', 'Controlled movements'],
    tipsTr: ['Kolları yere paralel tutun', 'Kürek kemiklerini sıkıştırın', 'Kontrollü hareket edin'],
  },

  // BACK (5)
  {
    id: 'pull_up',
    name: 'Pull Up',
    nameTr: 'Barfiks',
    description: 'The ultimate bodyweight back builder.',
    descriptionTr: 'Temel vücut ağırlığı sırt egzersizi.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['back', 'arms', 'core'],
    icon: '🦍',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Pull chest to bar', 'Engage lats first', 'Full extension at bottom'],
    tipsTr: ['Göğsünüzü bara doğru çekin', 'Önce kanat kaslarınızı kasın', 'En altta tam esneyin'],
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    nameTr: 'Lat Pulldown',
    description: 'Machine alternative to pull ups for lats.',
    descriptionTr: 'Kanat kasları için makine egzersizi.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['back', 'arms'],
    icon: '⬇️',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Lean back slightly', 'Pull to upper chest', 'Squeeze back at the bottom'],
    tipsTr: ['Hafifçe geriye yaslanın', 'Üst göğse doğru çekin', 'En altta sırtınızı sıkın'],
  },
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    nameTr: 'Barbell Row',
    description: 'Heavy compound row for back thickness.',
    descriptionTr: 'Sırt kalınlığı için ağır bileşik çekiş.',
    category: 'upper_body',
    difficulty: 'advanced',
    muscleGroups: ['back', 'arms', 'core'],
    icon: '🚣',
    defaultSets: 4,
    defaultReps: 8,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Keep back parallel to floor', 'Pull to belly button', 'Maintain neutral spine'],
    tipsTr: ['Sırtınızı yere paralel tutun', 'Göbek deliğinize doğru çekin', 'Omurganızı düz tutun'],
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    nameTr: 'Oturarak Kablo Çekiş',
    description: 'Machine row for mid-back and lats.',
    descriptionTr: 'Orta sırt ve kanatlar için oturarak çekiş.',
    category: 'upper_body',
    difficulty: 'beginner',
    muscleGroups: ['back', 'arms'],
    icon: '🚠',
    defaultSets: 3,
    defaultReps: 12,
    restSeconds: 60,
    cameraPosition: 'side',
    tips: ['Keep chest up', 'Do not rock back and forth', 'Squeeze shoulder blades together'],
    tipsTr: ['Göğsünüzü dik tutun', 'İleri geri sallanmayın', 'Kürek kemiklerini birbirine yaklaştırın'],
  },
  {
    id: 't_bar_row',
    name: 'T-Bar Row',
    nameTr: 'T-Bar Row',
    description: 'A close-grip heavy rowing exercise.',
    descriptionTr: 'Dar tutuşlu ağır sırt çekiş egzersizi.',
    category: 'upper_body',
    difficulty: 'intermediate',
    muscleGroups: ['back', 'arms', 'core'],
    icon: '⚔️',
    defaultSets: 3,
    defaultReps: 10,
    restSeconds: 90,
    cameraPosition: 'side',
    tips: ['Straddle the bar', 'Keep lower back tight', 'Use V-grip handle'],
    tipsTr: ['Barı bacaklarınızın arasına alın', 'Belinizi sıkı tutun', 'V-tutamak kullanın'],
  },
  
  // CARDIO / LOCOMOTION (1)
  {
    id: 'walking',
    name: 'Walking',
    nameTr: 'Yürüyüş',
    description: 'Basic walking locomotion to track steps and posture.',
    descriptionTr: 'Adım saymak ve duruşu takip etmek için temel yürüyüş.',
    category: 'lower_body',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'hamstrings', 'core'],
    icon: '🚶',
    defaultSets: 1,
    defaultReps: 100, // Represents steps for walking
    restSeconds: 0,
    cameraPosition: 'side',
    tips: ['Keep your chest up', 'Maintain a neutral spine', 'Swing arms naturally'],
    tipsTr: ['Göğsünüzü dik tutun', 'Omurganızı düz tutun', 'Kollarınızı doğal sallayın'],
  },
  // PILATES
  {
    id: 'pilates_hundred',
    name: 'Pilates Hundred',
    nameTr: 'Pilates Hundred',
    description: 'A classic Pilates mat exercise for core strength.',
    descriptionTr: 'Karın bölgesini güçlendiren klasik bir Pilates mat egzersizi.',
    category: 'pilates',
    difficulty: 'beginner',
    muscleGroups: ['core'],
    icon: '🧘',
    defaultSets: 1,
    defaultReps: 100,
    restSeconds: 30,
    cameraPosition: 'side',
    tips: ['Keep your lower back pressed to the mat', 'Pump your arms vigorously', 'Breathe in for 5, out for 5'],
    tipsTr: ['Belinizi mata bastırın', 'Kollarınızı omuzdan ritmik şekilde pompalayın', '5 sayıda nefes al, 5 sayıda ver'],
    demoUrl: 'https://media.giphy.com/media/l41YkxvU8c7J7Bba0/giphy.gif'
  },
  {
    id: 'pilates_roll_up',
    name: 'Pilates Roll Up',
    nameTr: 'Pilates Roll Up',
    description: 'Articulates the spine and strengthens the abdominals.',
    descriptionTr: 'Omurgayı esneten ve karın kaslarını güçlendiren bir hareket.',
    category: 'pilates',
    difficulty: 'intermediate',
    muscleGroups: ['core'],
    icon: '🧘',
    defaultSets: 3,
    defaultReps: 8,
    restSeconds: 45,
    cameraPosition: 'side',
    tips: ['Peel your spine off the mat one vertebra at a time', 'Keep legs straight and together', 'Use your core, not momentum'],
    tipsTr: ['Omurganızı yavaşça tek tek mattan ayırın', 'Bacaklarınızı düz ve bitişik tutun', 'Hızlanmadan, karın kaslarınızla kalkın'],
    demoUrl: 'https://media.giphy.com/media/l41YkxvU8c7J7Bba0/giphy.gif'
  },
  {
    id: 'pilates_bridge',
    name: 'Pilates Bridge',
    nameTr: 'Pilates Köprü',
    description: 'Improves hip mobility and glute strength.',
    descriptionTr: 'Kalça mobilitesini ve glute gücünü artırır.',
    category: 'pilates',
    difficulty: 'beginner',
    muscleGroups: ['glutes', 'core'],
    icon: '🧘',
    defaultSets: 3,
    defaultReps: 15,
    restSeconds: 30,
    cameraPosition: 'side',
    tips: ['Tuck your pelvis and roll up', 'Squeeze glutes at the top', 'Roll down smoothly'],
    tipsTr: ['Kalçanızı sıkarak yavaşça yukarı kalkın', 'Tepe noktasında kalçanızı sıkın', 'Omurganızı tek tek yere indirin'],
    demoUrl: 'https://media.giphy.com/media/l41YkxvU8c7J7Bba0/giphy.gif'
  }
];
